services:
  bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - elasticsearch
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ELASTIC_URL=http://elasticsearch:9200
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DATABASE_URL=postgresql+asyncpg://user:password@db/botdb

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=botdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data:
