name: Super-Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v6.6.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_LARGE_FILES: false
